#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


yabai -m config window_placement second_child

# yabai -m config external_bar all:30:0
# yabai -m config menubar_opacity 0.0

yabai -m config external_bar               all:00:0     \
                mouse_follows_focus        on          \
                focus_follows_mouse        autofocus          \
                window_zoom_persist        off          \
                window_placement           second_child \
                menubar_opacity            1.0          \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.2          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                window_animation_duration  0.3          \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                auto_padding               on           \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                5           \
                bottom_padding             5            \
                left_padding               5            \
                right_padding              5            \
                window_gap                 5



yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Archive Utility|Python|LibreOffice|App Store|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m rule --add  label=".*Layout|Open" app="^yEd$" title=".*Layout|Open" manage=off

# yabai -m rule --add app="^KeePassXC$" manage=off


yabai -m config layout bsp

echo "yabai configuration loaded.."
