#!/bin/bash

source "$DOTFILES/sketchybar.config/colors.sh" # Loads all defined colors
source "$DOTFILES/sketchybar.config/icons.sh" # Loads all defined colors

ITEM_DIR="$DOTFILES/sketchybar.config/items" # Directory where the items are configured
PLUGIN_DIR="$DOTFILES/sketchybar.config/plugins" # Directory where all the plugin scripts are stored

PADDINGS=3 # All paddings use this value (icon, label, background)

FONT="SF Pro"

bar=(
  height=35
  color=$BAR_COLOR
  border_width=2
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=-5
  margin=-2
  topmost=window
)

sketchybar --bar "${bar[@]}"

# sketchybar --bar position=top height=30 blur_radius=30 color=0x40000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

# default=(
#   padding_left=5
#   padding_right=5
#   icon.font="Hack Nerd Font:Bold:14.0"
#   label.font="Hack Nerd Font:Bold:14.0"
#   icon.color=0xffffffff
#   label.color=0xffffffff
#   icon.padding_left=4
#   icon.padding_right=4
#   label.padding_left=4
#   label.padding_right=4
# )

defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:11.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
# source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

# Center
# source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/media.sh"

# Right
source "$ITEM_DIR/calendar.sh"
# source "$ITEM_DIR/wifi.sh"
# source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/cpu.sh"

sketchybar --add alias "OpenVPN Connect,Item-0" right
sketchybar --add alias "Control Center,WiFi" right
# "OpenVPN Connect,Item-0",
# "TextInputMenuAgent,Item-0",
# "Control Center,Display",
# "Control Center,Sound",
# "Control Center,KeyboardBrightness",
# "Control Center,Battery",
# "Control Center,WiFi",
# "Control Center,UserSwitcher",
# "Control Center,BentoBox",
# "Control Center,Clock"





# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
#
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=7
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done



##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

# sketchybar --add item chevron left \
#            --set chevron icon= label.drawing=off \
#            --add item front_app left \
#            --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
#            --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

# sketchybar --add item clock right \
#            --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
#            --add alias "Control Center,Wifi" right \
#            --add item volume right \
#            --set volume script="$PLUGIN_DIR/volume.sh" \
#            --subscribe volume volume_change \
#            --add item battery right \
#            --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#            --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
# sketchybar --hotload on

# sketchybar --update

echo "sketchybar configuation loaded.."
