export ZDOTDIR=~/.config/zsh

export EDITOR="nvim"
export VISUAL="nvim"
export DOTFILES=$(echo ~)/.dotfiles

# History in cache directory:
export HISTFILE=$ZDOTDIR/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

export MANPAGER='nvim +Man!'


export PATH=$DOTFILES/bin:$HOME/.local/bin:$PATH
export PATH=~/.config/emacs/bin:$PATH
