return {
    -- 'ms-jpq/coq_nvim',
    -- branch = 'coq',
    --
    -- dependencies  = {
    --     'ms-jpq/coq.artifacts',
    --     branch = 'artifacts'
    -- },
    --
    -- init = function ()
    --     vim.g.coq_settings = {
    --         auto_start = true,
    --         keymap = {
    --             recommended = false,
    --             pre_select = true
    --         },
    --         display = {
    --             ghost_text = {enabled = false}
    --         },
    --         -- clients = {
    --           -- lsp = {
    --                 -- enabled = true,
    --                 -- always_on_top = { "True" },
    --                 -- resolve_timeout = 0.06,
    --                 -- short_name = "lsp",
    --                 -- weight_adjust = 0.5,
    --             -- },
    --         -- },
    --     }
    --
    --     vim.api.nvim_set_keymap('i', '<Esc>', 'pumvisible() ? "<C-e><Esc>" : "<Esc>"', {expr = true, silent = true})
    --     vim.api.nvim_set_keymap('i', '<C-c>', 'pumvisible() ? "<C-e><C-c>" : "<C-c>"', {expr = true, silent = true})
    --     vim.api.nvim_set_keymap('i', '<BS>', 'pumvisible() ? "<C-e><BS>" : "<BS>"', {expr = true, silent = true})
    --     vim.api.nvim_set_keymap('i', '<CR>', 'pumvisible() ? (complete_info().selected == -1 ? "<C-e><CR>" : "<C-y>") : "<CR>"', {expr = true, silent = true})
    -- end
}
