# Focus monitor
bind = $mainMod, comma, focusmonitor, -1
bind = $mainMod, period, focusmonitor, +1

# Set master window size (between 5% and 95%)
bind = $mainMod, m, layoutmsg, resize 0.05
bind = $mainMod, i, layoutmsg, addmaster
bind = $mainMod, d, layoutmsg, removemaster
bind = $mainMod, Return, layoutmsg, swapwithmaster

bind = SUPER, f, fullscreen
bind = $mainMod, Space, togglefloating

# Define the key to enter the submap
# bind = $mainMod, G, submap, group
bind = $mainMod, t, togglegroup
bind = $mainMod, u, moveoutofgroup

bind = $mainMod, p, pin
bind = $mainMod, c, centerwindow

bind = $mainMod, n, cyclenext
bind = $mainMod, p, cyclenext, prev

bind = $mainMod, i, changegroupactive, b
bind = $mainMod, o, changegroupactive, f

# binde = $mainMod SHIFT, i, moveintogroup, l
# binde = $mainMod SHIFT, o, moveintogroup, r

binde = $mainMod SHIFT, h, movewindoworgroup, l
binde = $mainMod SHIFT, l, movewindoworgroup, r
binde = $mainMod SHIFT, k, movewindoworgroup, u
binde = $mainMod SHIFT, j, movewindoworgroup, d


bind = $mainMod SHIFT, o, resizeactive, 50 0
bind = $mainMod SHIFT, i, resizeactive, -50 0

# bind = $mainMod, k, cyclenext
# bind = $mainMod, j, cyclenext, prev

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Mouse binds
bindm = ALT, mouse:272, movewindow
bindm = ALT, mouse:273, resizewindow


bind = $mainMod, r, submap, resize
submap = resize
bind = , h, resizeactive, -50 0
bind = , l, resizeactive, 50 0
bind = , k, resizeactive, 0 -50
bind = , j, resizeactive, 0 50
bind = , escape, submap, reset
bind = , return, submap, reset
submap = reset

bind = $mainMod, m, submap, move
submap = move
bind = , h, moveactive, -50 0
bind = , l, moveactive, 50 0
bind = , k, moveactive, 0 -50
bind = , j, moveactive, 0 50
bind = , escape, submap, reset
bind = , return, submap, reset
submap = reset
