export EDITOR="nvim"
export DOTFILES=$(echo ~)/dotfiles

if [[ $OSTYPE == 'darwin'* ]]; then
    export SCALA_HOME=/opt/homebrew/bin/scala
    export JAVA_HOME=`/usr/libexec/java_home -v 17`
fi
#export ORACLE=/Users/hulu/Downloads/instantclient_18_1
export ORACLE_HOME=/opt/instantclient_19_8
export TNS_ADMIN=$ORACLE_HOME/network/admin
export LD_LIBRARY_PATH=$ORACLE_HOME



export PATH=$HOME/.local/bin:~/dotfiles/bin:/usr/local/node-v18.15.0-darwin-x64/bin:$PATH

export kabinet='linux.inf.u-szeged.hu'
#export tanszek='/Volumes/Common/team/columbus/exchange/aattila/'
export sedbl='sedbl02.inf.u-szeged.h'

export ZDOTDIR=~/.config/zsh
