monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "bluez_output*"
      }
    ]
    actions = {
      update-props = {
        # node.disabled = true
        node.description = "Bluetooth"
      }
    }
  }

]
